package com.example;

import java.util.ArrayList;
import java.util.List;

public class JokeStore {

    private List<String> mJokes;

    protected JokeStore() {

        mJokes = new ArrayList<>();
        mJokes.add("Chuck Norris only created Russians so he can use them to take over TGI Fridays.");
        mJokes.add("Chuck Norris once roundhouse kicked a man so hard it broke the space/time continuum and killed the dinosaurs.");
        mJokes.add("Chuck Norris won\u0027t beat the crap out of you, he\u0027ll beat the DNA out of you.");
        mJokes.add("Chuck Norris goes from 0 to kick ass in. . ., well, he doesn\u0027t actually have zero, he pretty much just has kick ass.");
        mJokes.add("There once was a young Irish woman who went to confession. Upon entering \r\nthe confessional she said, \"Forgive me Father, for I have sinned.\" The \r\npriest said, \"Confess your sins and be forgiven.\" The young woman said, \r\n\"Last night my boyfriend made mad passionate love to me seven times.\"\r\nThe priest thought long and hard and then said, \"Take seven lemons and \r\nsqueeze them into a glass and then drink it.\"\r\nThe young woman asked, \"Will this cleanse me of my sins?\"\r\nThe priest said \"NO, but it will wipe the smile off of your face.\"");
        mJokes.add("Chuck Norris knows the value of NULL, and he can sort by it too.");
        mJokes.add("If you put Chuck Norris as your profile picture on facebook thousands of supermodels will friend you each day.");
        mJokes.add("Chuck Norris chopped a tree down with a roundhouse kick.");
        mJokes.add("Adam and Eve weren\u0027t the first people on Earth, Chuck Norris just kept a low profile.");
        mJokes.add("What kind of ant is good at maths ?\nAn accountant !");
        mJokes.add("The best security system for a bank is when Chuck\u0027s money is in it.");
        mJokes.add("Chuck Norris can literally catch a falling star and put it in his pocket.");
        mJokes.add("It was Chuck Norris not David that slew Goliath and he did it with his round house kick not a slingshot.");
        mJokes.add("The reason why batman only comes out at night is because he\u0027s afraid he might encounter Chuck Norris in the Morning and afternoon.");
        mJokes.add("The 98 year old Mother Superior from Ireland was dying. The nuns gathered around her bed trying to make her last journey comfortable. They gave her some warm milk to drink but she refused. Then one of the nuns took the glass back to the kitchen. Remembering a bottle of Irish whiskey received as a gift the previous Christmas, she opened and poured a generous amount into the warm milk. Back at Mother Superior`s bed, she held the glass to her lips. Mother drank a little, then a little more and before they knew it, she had drunk the whole glass down to the last drop. \"Mother,\" the nuns asked with earnest, \"please give us some wisdom before you die.\"\nShe raised herself up in bed and with a pious look on her face said, \"Don`t sell that cow.");
        mJokes.add("TO MY DARLING HUSBAND,\n\nI am sending you this letter via this email communications thing, so that you will be sure to read it.  Please forgive the deception, but I thought you should know what has been going on at home since your computer entered our lives FIVE YEARS AGO.  The children are doing well. Billy is ten now and is a bright, handsome boy.  He has developed quite an interest in the arts.  He drew a family portrait for a school project, all the figures were good, and the back of your head is very realistic.  You should be very proud of him.\n\nLittle Jennifer turned six in September.  She looks a lot like you did at that age.  She is an attractive child and quite smart.  She still remembers that you spent the whole afternoon with us on her birthday.  What a grand day for Jenny, despite the fact that it was stormy and the electricity was out.\n\nI am doing well.  I went blonde about a year ago, and discovered that it really is more fun!  George, I mean, Mr.  Wilson the department head, has uh, taken an interest in my career and has become a good friend to us all.\n\nI discovered that the household chores are much easier since I realized that you didn\u0027t mind being vacuumed but that feather dusting made you sneeze.  The house is in good shape.  I had the living room painted last spring; I\u0027m sure you noticed it.  I made sure that the painters cut holes in the drop sheet so you wouldn\u0027t be disturbed.\n\nWell, my dear, I must be going.  Uncle George, uh, Mr.  Wilson, I mean, is taking us all on a ski trip and there is packing to do.  I have hired a housekeeper to take care of things while we are away, she\u0027ll keep things in order, fill your coffee cup and bring your meals to your desk, just the way you like it.  I hope you and the computer will have a lovely time while we are gone.  Billy, Jenny and I will think of you often.  Try to remember us while your disks are booting.\n\nHappy Valentines Day!\n\nLove, Kate");
        mJokes.add("Rudolf only has a red nose cus of Chuck\u0027s roundhouse kick.");
        mJokes.add("When there is a big lightening, Chuck Norris is talking to Dzeus.");
        mJokes.add("Bees sting Chuck Norris for a less painful death.");
        mJokes.add("Chuck Norris fought the law... he kicked it\u0027s ass!");
        mJokes.add("Chuck Norris knows what the secret crabby patty recipe is.");
        mJokes.add("Chuck Norris only needs one (1) pokeball to catch legendery pokemon.");
        mJokes.add("New Chemical Element Discovered\r\n     \r\n   \r\nThe heaviest element known to science was recently discovered by\r\ninvestigators at a major U.S. research university. The element, tentatively\r\nnamed administratium, has no protons or electrons and thus has an atomic\r\nnumber of 0. However, it does have one neutron, 125 assistant neutrons, 75\r\nvice neutrons and 111 assistant vice neutrons, which gives it an atomic mass\r\nof 312. These 312 particles are held together by a force that involves the\r\ncontinuous exchange of meson-like particles called morons.\r\nSince it has no electrons, administratium is inert. However, it can be\r\ndetected chemically as it impedes every reaction it comes in contact with.\r\nAccording to the discoverers, a minute amount of administratium causes one\r\nreaction to take over four days to complete when it would have normally\r\noccurred in less than a second.\r\nAdministratium has a normal half-life of approximately three years, at which\r\ntime it does not decay, but instead undergoes a reorganization in which\r\nassistant neutrons, vice neutrons and assistant vice neutrons exchange places.\r\nSome studies have shown that the atomic mass actually increases after each\r\nreorganization.\r\nResearch at other laboratories indicates that administratium occurs naturally\r\nin the atmosphere. It tends to concentrate at certain points such as\r\ngovernment agencies, large corporations, and universities. It can usually be\r\nfound in the newest, best appointed, and best maintained buildings.\r\nScientists point out that administratium is known to be toxic at any level of\r\nconcentration and can easily destroy any productive reaction where it is\r\nallowed to accumulate. Attempts are being made to determine how administratium\r\ncan be controlled to prevent irreversible damage, but results to date are not\r\npromising.");
        mJokes.add("A coincidence is when God performs a miracle, and decides to remain anonymous.\"");
        mJokes.add("Q: What is the difference between a single 40-year-old\r\n   woman and a single 40-year-old man? A: The 40-year-old woman thinks\r\n   often of having children and the man thinks often about dating them.");
        mJokes.add("A man decides to take the opportunity while his wife is away to paint\r\n   the toilet seat. The wife comes home sooner than expected, sits, and\r\n   gets the seat stuck to her rear. She is understandably distraught\r\n   about this and asks her husband to drive her to the doctor. She puts\r\n   on a large overcoat so as to cover the stuck seat, and they go.\r\n   \r\n   When they get to the doctor\u0027s, the man lifts his wife\u0027s coat to show\r\n   their predicament. The man asks, \"Doctor, have you ever seen anything\r\n   like this before?\"\r\n   \r\n   \"Well, yes,\" the doctor replies, \"but not framed like that.\"");
        mJokes.add("jonson theeee weeeed is not as good as Chuck Norris. chuck has a massive penis.");
        mJokes.add("Under chuck Norris\u0027 Beard is not a chin......Only Another Fist.");
        mJokes.add("This blond teenage dragged her boyfriend to the court on paternity issue.\r\nThe lawyer asked, \"How long are you having a sexual relationship?\" \"Years,\r\nI tell you years\" she replied. \" Thats no answer, you have to specify how\r\nlong has he intimated with you.\" \"I don\u0027t know exactly, its average, about\r\nsix inches\"");
        mJokes.add("Anton Chigurh (from No Country for Old Men) needed the money to pay Chuck Norris to spare his life.");
        mJokes.add("The teacher walks in and finds an apple on her desk with the letters \"ILU\" \r\nwritten on it. The teacher asks who left it. A little white girl raises \r\nher hand. Well sweetie, what does \"ILU\" mean? The little girl replies, \"I \r\nlove you.\"\r\nThe teacher says, \"Isn\u0027t that sweet,\" and continues with class. The next \r\nday the teacher finds a banana on her desk with the letters \"YAS\" written \r\non it. The teacher asks who left and what does it mean. A little white boy \r\nraises his hand and says, \"It means, You are special.\" \"Thank you \r\nsweetheart\", the teacher says.\r\nThe following day, the teacher walks in to find a watermelon with the \r\nletters \"FUCK\" written on it. The enraged teacher asks who left it and if \r\nthey know what that means. A little black girl raises her hand and \r\ncheerfully says, \"Yes maam, I left it. It means, from us colored kids!\".");
        mJokes.add("Chuck Norris lost both his legs in a car accident....and still managed to walk it off.");
        mJokes.add("Chuck Norris is the only person who can write history of the future.");
        mJokes.add("Chuck Norris could read a Japanese textbook in 29 seconds.");
        mJokes.add("An elderly couple walk into a doctor\u0027s office. The man tells the\r\n   doctor, \"Doctor, we want\r\n   to have a baby.\" The doctor replies,\"At your age I don\u0027t think it\u0027s\r\n   possible, but I\u0027ll give\r\n   you a jar, come back in a few days with a sperm sample.\" So the couple\r\n   comes back a few\r\n   days later.They give the doctor an empty jar. The doctor says,\"I was\r\n   afraid of this.\" The\r\n   old man says,\"No, it\u0027s not what you think. I tried it with my left\r\n   hand. I tried it with my\r\n   right hand. She tried it with her left hand. She tried it with her\r\n   right hand. She tried it with\r\n   her teeth in. She tried it with her teeth out. But we couldn\u0027t get the\r\n   lid off the jar.\"");
        mJokes.add("Every time Chuck Norris blinks, a star is created.");
        mJokes.add("Chuck Norris can make an omelette without breaking any eggs.");
        mJokes.add("If Chuck Norris throws a ball into the sky, it won\u0027t come down to earth for another 104 years.");
        mJokes.add("The pursuit of happiness is after Chuck Norris.");
        mJokes.add("A guy is down on his luck. He takes his last $500 and goes to Las Vegas.\r\nOvernight, he has a fantastic run of luck. He stumbles out of the casino\r\nand finds a pay phone. He calls his wife and says, \"Honey, pack your bags.\r\nI just won over a million dollars in Vegas.\"\r\nHis wife say, \"That\u0027s wonderful. What should I pack for...Europe, the Carribean?\"\r\nHe says, \"I don\u0027t care, just be gone when I get home.\"");
        mJokes.add("Q: Why do women wake up with a brain the size of a pea?\r\nA: It swells up over night.");
        mJokes.add("Cocoa puffs go cuckoo for Chuck Norris.");
        mJokes.add("A coincidence is when God performs a miracle, and decides to remain anonymous.\"");
        mJokes.add("Chuck Norris can make the Cookie Monster Diet.");
        mJokes.add("Rabbit\u0027s Ph.D. Thesis:\r\n                                A Parable for Graduate Students\r\nScene: It\u0027s a fine sunny day in the forest, and a rabbit is sitting outside\r\nhis burrow, tippy-tapping on his typewriter.\r\nAlong comes a fox, out for a walk.\r\nFox: \"What are you working on?\"\r\nRabbit: \"My thesis.\"\r\nFox: \"Hmmm. What\u0027s it about?\"\r\nRabbit: \"Oh, I\u0027m writing about how rabbits eat foxes.\"\r\n(incredulous pause)\r\nFox: \"That\u0027s ridiculous! Any fool knows that rabbits don\u0027t eat foxes.\"\r\nRabbit: \"Sure they do, and I can prove it. Come with me.\"\r\nThey both disappear into the rabbit\u0027s burrow. After a few minutes, the\r\nrabbit returns, alone, to his typewriter and resumes typing.\r\nSoon, a wolf comes along and stops to watch the hardworking rabbit.\r\nWolf: \"What\u0027s that you\u0027re writing?\"\r\nRabbit: \"I\u0027m doing a thesis on how rabbits eat wolves.\"\r\n(loud guffaws)\r\nWolf: \"You don\u0027t expect to get such rubbish published, do you?\"\r\nRabbit: \"No problem. Do you want to see why?\"\r\nThe rabbit and the wolf go into the burrow, and again the rabbit\r\nreturns by himself, after a few minutes, and goes back to typing.\r\nScene: Inside the rabbit\u0027s burrow. In one corner, there is a pile of fox \r\nbones.  In another corner, a pile of wolf bones. On the other side of the \r\nroom, a huge lion is belching and picking his teeth.\r\n   (The End)\r\n Moral:\r\n    It doesn\u0027t matter what you choose for a thesis subject.\r\n    It doesn\u0027t matter what you use for data.\r\n    What does matter is who you have for a thesis advisor.");
        mJokes.add("Chuck Norris bite the Macintosh Apple.");
        mJokes.add("Chuck Norris doesn\u0027t follow the green cross code, drivers follow the Chuck Norris cross code.");

    }

    public String getJoke(int position){
        return mJokes.get(position);
    }

    public int getCount(){
        return mJokes.size();
    }
}
